sigoden/llm-functions

sh/get_web_page.sh
Closes https://github.com/sigoden/llm-functions/issues/10
The majority of non text content is stripped from the HTML using pandoc's native features and sed, this should save tokens.
=> feat: add `get_web_page`

Argcfile.sh
The bash path is incorrect, so when I run the command script, it throws an error.
```
C:\w\llm-functions\cmd\cmd.sh: line 19: cygpath: command not found
```
This pr fixs this bug.
```diff
-- "C:\Program Files\Git\usr\bin\bash.exe"
++ "C:\Program Files\Git\bin\bash.exe"
```
=> fix: incorrect bash path in generated `.cmd` files

Argcfile.sh, README.md
Instead of useing `embeddings` dir, we add `documents` field to agent definition file `index.yaml`.
```diff
documents:
- files/doc.pdf
```
=> feat: agent rag use `documents` field other than `embeddings` dir

.gitignore, Argcfile.sh
web_search and code_interperter are most common tools. We provide two argc commands to symlink them with tools.
```
argc link-web-search search_bing.sh
argc link-code-interpreter execute_py_code.py 
```
=> feat: link web_search/code_interperter tools

agents/coder/tools.sh, tools/fs_cat.sh, tools/fs_ls.sh, tools/fs_mkdir.sh, tools/fs_rm.sh, tools/fs_write.sh
`FS_BASE_DIR`  does not work properly, see https://github.com/sigoden/llm-functions/pull/70#issuecomment-2265198017
We are changing to a new security policy:
- Always allow read operations.
- Always allow write operations that only affect the current directory.
- For other operations, prompt for confirmation.
=> feat: prompt confirmation for fs write operations outside cwd

agents/coder/index.yaml, agents/coder/tools.sh
=> refactor: improve coder agent

Argcfile.sh, README.md
Hello,
I installed aichat with brew on my mac. The symlink for functions_dir getting wrong directory, here the 
echo "$(aichat --info | grep -w functions_dir | awk '{print $2}')"
/Users/<home>/Library/Application
instead of /Users/<home>/Library/Application Support.
I fixed it.
=> fix: extraction of functions_dir for symlink

scripts/run-agent.js, scripts/run-agent.py, scripts/run-agent.sh, scripts/run-tool.js, scripts/run-tool.py, scripts/run-tool.sh
We use environment variables to control this.
`LLM_TOOL_DUMP_RESULT=1`: Dump results from all tools.
`LLM_TOOL_DUMP_RESULT_<TOOL_NAME>=1`: Dump result from the `TOOL_NAME` tool.
`LLM_AGENT_DUMP_RESULT_<AGENT_NAME>=1`: Dump results from all tools of the `AGENT_NAME` agent.
`LLM_AGENT_DUMP_RESULT_<AGENT_NAME>_<FN_NAME>=1`: Dump results from the `FN_NAME` tool of the `AGENT_NAME` agent.
close #110
=> feat: controls displaying the results from function call

.gitignore, Argcfile.sh
After the PR merged, llm-functions will works with python virtualenv. 
The only thing you need to do is make sure the virtualenv path is `.venv`. Users can set up the venv using the following command.
```
python -m venv .venv
```
close #115
=> feat: support python virtualenv

agents/coder/index.yaml, agents/coder/tools.sh, agents/coder/tools.txt, agents/todo/tools.sh, scripts/declarations-util.sh, scripts/run-agent.sh, scripts/run-tool.sh, tools/execute_command.sh, tools/execute_sql_code.sh, tools/fs_patch.sh, tools/fs_rm.sh, tools/fs_write.sh, tools/search_wikipedia.sh, tools/send_twilio.sh, utils/guard_operation.sh, utils/guard_path.sh, utils/patch.awk
- extract utils/guard_path.sh
- extract utils/guard_operation.sh
- pipe error to stderr
- prepend `error: ` prefix to all error messages
=> refactor: improve bash code

Argcfile.sh, agents/demo/tools.js, scripts/create-tool.sh, scripts/run-agent.js, scripts/run-agent.py, scripts/run-agent.sh, scripts/run-tool.js, scripts/run-tool.py, scripts/run-tool.sh, tools/demo_js.js, tools/execute_js_code.js
- js export expression
- check args regarding run-agent/run-tool
=> refactor: several improvements

tools/web_search_aichat.sh
cohere chat v2 api don't support web search.
=> refactor: update web_search_aichat.sh

mcp/server/README.md, mcp/server/index.js, mcp/server/package.json
Let LLM-functions tools/agents be used through the Model Context Protocol.
=> feat: add mcp server

scripts/run-agent.sh, scripts/run-mcp-tool.sh, scripts/run-tool.sh
Git bash for windows does not handle slashes correctly, it converts double slashes to single slash for json.
The command to inspect the bug.
```
PS> & 'C:\Program Files\Git\usr\bin\bash.exe' dump.sh '{"path":"C:\\file"}'
{"path":"C:\file"}
```
The contect of `dump.sh`.
```sh
printf "%s\n" "$@"
```
This PR replaces single blackslash to double blackslashs to avoid the bug.
=> fix: git bash on windows backslashs bug

Argcfile.sh, docs/environment-variables.md, scripts/run-agent.js, scripts/run-agent.py, scripts/run-agent.sh, scripts/run-mcp-tool.sh, scripts/run-tool.js, scripts/run-tool.py, scripts/run-tool.sh
`LLM_DUMP_RESULTS`: Controls whether to print the execution results of the tool, e.g. `get_current_weather\|fs.*\|todo:.*`, `.*`
This PR replaced #111
=> feat: support env var `LLM_DUMP_RESULTS`

mcp/bridge/README.md, mcp/bridge/index.js
To avoid name clashes, The server automatically prefix tool names with `<server>_`. You can disable this behavior by add `prefix: false` to server configuration.
=> feat(mcp): add `prefix` filed to  bridge server configuraiton

docs/environment-variables.md, scripts/run-mcp-tool.sh
By default, llm-functions will ask confirm before executing the mcp tools.
Controls whether to prompt for confirmation before executing certain tools, e.g., `git_commit\|git_reset`, `.*` 
Controls whether to bypass confirmation requests for certain tools, e.g., `git_status\|git_diff.*`, `.*`
=> feat(mcp): add LLM_MCP_NEED_CONFIRM and LLM_MCP_SKIP_CONFIRM

mcp/bridge/index.js, scripts/mcp.sh
```diff
...
{
"name": "fs_read_file",
"description": "Read the complete contents of a file from the file system. Handles various text encodings and provides detailed error messages if the file cannot be read. Use this tool when you need to examine the contents of a single file. Only works within allowed directories.",
"parameters": {
"type": "object",
"properties": {
"path": {
"type": "string"
}
},
"required": [
"path"
],
"additionalProperties": false,
"$schema": "http://json-schema.org/draft-07/schema#"
},
-    "mcp": true
+    "mcp": "fs"
}
...
```
=> refactor(mcp): change to `mcp: <name>` for mcp tool declarations

agents/sql/README.md, agents/sql/index.yaml, agents/sql/tools.sh, tools/execute_sql_code.sh
An AI agent that helps you manage a SQL database.
=> feat: add sql agent

mcp/server/index.js
- fixed tool response format to follow MCP spec (https://spec.modelcontextprotocol.io/specification/server/tools/#calling-tools)
- after the change CLaude Desktop works as expected with MCP-Server
=> fix output msg format

scripts/run-agent.js, scripts/run-agent.py, scripts/run-tool.js, scripts/run-tool.py
Make it easier to identify errors
=> refactor: improve run-agent/run-agent scripts

scripts/mcp.sh
Solved https://github.com/sigoden/aichat/issues/1050#issuecomment-2648925705
=> feat(mcp): auto install deps before starting mcp bridge server

agents/json-viewer/package.json, agents/json-viewer/tools.js
json-viewer depends on the node-jq package, but it requires downloading the jq binary from the internet and has limited platform support. After this PR merged, json-viwer will rely on the jq already installed on the platform, which is more convenient and  compatible with more platforms.
relate to #159
=> feat(agents): json-viewer use jq cli other than node-jq module
