sigoden/llm-functions

- Argcfile.sh
> fix: install failed since wrong aichat version

- Argcfile.sh
- README.md
- cmd/cmd.js
- cmd/cmd.py
- cmd/cmd.rb
- cmd/cmd.sh
- sh/get_current_time.sh
- sh/may_execute_command.sh
AIChat pass JSON data directly as first positional argument to function tools
```
may_execute_command '{"command":"echo \"hello world\""}' 
```
following sigoden/aichat#528
> feat: rewrite to accept json data from cli args other than env var

- tools/send_mail.sh
```
$  aichat -r %functions% come out a joke and send it to poteno4830@crodity.com
Call send_mail '{"recipient":"poteno4830@crodity.com","subject":"Funny Joke","body":"Why do we tell actors to 'break a leg'? Because every play has a cast!"}'
```
> feat: add send_mail.sh

- Argcfile.sh
When run `argc run-tool` without the json data, argc will guide your to input the data.
> feat: `argc run-tool` helps you input json data

- Argcfile.sh
- scripts/create-tool.sh
- scripts/declarations-util.sh
```
USAGE: Argcfile <COMMAND>
COMMANDS:
run@tool                    Run the tool [aliases: tool:run]
run@bot                     Run the bot [aliases: bot:run]
build                       Build the project
build@tool                  Build tools [aliases: tool:build]
build-bin@tool              Build tools to bin [aliases: tool:build-bin]
build-declarations@tool     Build tools function declarations file [aliases: tool:build-declarations]
generate-declarations@tool  Generate function declaration for the tool [aliases: tool:generate-declarations]
build@bot                   Build bots [aliases: bot:build]
build-bin@bot               Build bots to bin [aliases: bot:build-bin]
build-declarations@bot      Build bots function declarations file [aliases: bot:build-declarations] …
```
> refactor: improve Argcfile.sh

- Argcfile.sh
- README.md
> fix: install to aichat functions_dir

- Argcfile.sh
```
get_current_time.sh
get_web_page.sh
#may_execute_command.sh
save_file.sh
get_current_weather.sh
```
```
todo-sh
#todo-py
```
close #47
> feat: tools.txt/agents.txt support comments

- tools/send_mail.sh
Use curl to send mail, Get rid fo mutt deps.
> refactor: tools/send_mail.sh with curl

- README.md
- agents/demo/README.md
- agents/demo/index.yaml
> refactor: demo agent with `LLM_AGENT_VAR_*`

- agents/prompt/README.md
- agents/prompt/index.yaml
> feat: add prompt agent

- tools/execute_sql_code.sh
> feat(tool): add execute_sql_code

- README.md
- tools/web_search_tavily.sh
- tools/web_search_vertexai.sh
> feat(tool): add web_search_vertexai.sh

- Argcfile.sh
- agents/coder/tools.sh
- tools/fs_rm.sh
- tools/fs_write.sh
improve `_guard_path` to use `realpath -m <path>` to get absolute path.
> refactor: improve `fs_*`

- scripts/run-agent.js
- scripts/run-agent.py
- scripts/run-agent.sh
> refactor: support LLM_AGENT_DUMP_RESULT

- tools/fs_patch.sh
- tools/fs_write.sh
- utils/patch.awk
> feat(tools): add fs_patch.sh

- tools/execute_js_code.js
- tools/execute_py_code.py
> fix: execute js/py code

- tools/fs_write.sh
> feat(tool): fs_write ask confirmation for existing files

- Argcfile.sh
- README.md
- docs/argcfile.md
- scripts/check-deps.sh
- scripts/mcp.sh
We can run `argc check` to ensure that everything is ready (environment variables, Node/Python dependencies, mcp-bridge server)
> feat: support check-related features

- scripts/check-deps.sh
> feat(script): check-deps will prompt user to install dependencies

- tools/web_search_aichat.sh
**LLMs support web-search:**
- gemini:gemini-2.0-*
- vertexai:gemini-*
- perplexity:*
- ernie:*
> feat(tool): update web_search_aichat.sh

- mcp/bridge/README.md
Create a `mcp.json`, not `mpc.json`.
> chore: update README.md

- scripts/mcp.sh
> fix: mcp.sh build-bin

- Argcfile.sh
- scripts/mcp.sh
> fix: argc build reserve mcp functions
